SELECT 
    "EmployeeID" as employee_id,
    "FirstName" as first_name,
    "LastName" as last_name,
    "Gender" as gender,
    "Age" as age,
    "BusinessTravel" as business_travel_frequency,
    "Department" as department,
    "DistanceFromHome (KM)" as distance_from_home,
    "State" as state,
    "Ethnicity" as ethnicity,
    "Education" as education_level,
    "EducationField" as education_field,
    "JobRole" as job_role,
    "MaritalStatus" as marital_status,
    "Salary" as salary,
    "StockOptionLevel" as stock_option_level,
    "OverTime" as is_paid_over_time,
    "HireDate" as hire_date,
    "Attrition" as is_attrition,
    "YearsAtCompany" as years_at_company,
    "YearsInMostRecentRole" as years_in_most_recent_role,
    "YearsSinceLastPromotion" as years_since_last_promotion,
    "YearsWithCurrManager" as years_with_current_manager
FROM {{ source('staging', 'stg_dev_employee') }} as e