version: 2

models:
  - name: dim_employee
    description: "employee dimension table"
    columns:
      - name: employee_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null